export enum EmailTypeEnum {
  RESET_PASSWORD = "reset-password",
  DELETE = "delete",
  OLD_VISIT = "old-visit",
  MANAGER_REVIEW = "manager-review",
  VERIFIED = "verified",
  LISTING_APPROVED = "ad-approved",
  LISTING_EDITING = "ad-editing",
  PREMIUM_ACTIVATED = "premium_activated",
  ACCOUNT_BANNED = "account_banned",
  WELCOME = "welcome",
  ACCOUNT_UNBANNED = "account_unbanned",
  LOGOUT = "logout",
  BRAND_MODEL_REQUEST = "brand-model-request",
  LISTING_INACTIVE = "ad-inactive",
}
