import dotenv from "dotenv";

dotenv.config();

export const config = {
  PORT: process.env.PORT || 3000,
  HOST: process.env.HOST || "localhost",
  MONGO_URL: process.env.MONGO_URL || "",

  JWT_ACCESS_SECRET: process.env.JWT_ACCESS_SECRET,
  JWT_ACCESS_EXPIRATION: process.env.JWT_ACCESS_EXPIRATION,
  JWT_REFRESH_SECRET: process.env.JWT_REFRESH_SECRET || "refresh_secret",
  JWT_REFRESH_EXPIRATION: process.env.JWT_REFRESH_EXPIRATION,

  ACTION_FORGOT_PASSWORD_SECRET: process.env.ACTION_FORGOT_PASSWORD_SECRET,
  ACTION_FORGOT_PASSWORD_EXPIRATION:
    process.env.ACTION_FORGOT_PASSWORD_EXPIRATION,
  ACTION_VERIFY_SECRET: process.env.ACTION_VERIFY_SECRET,
  ACTION_VERIFY_EXPIRATION: process.env.ACTION_VERIFY_EXPIRATION,
  ACTION_DELETE_SECRET: process.env.ACTION_DELETE_SECRET,
  ACTION_DELETE_EXPIRATION: process.env.ACTION_DELETE_EXPIRATION,

  FRONT_URL: process.env.FRONT_URL,
  FRONT_URL_OLD_VISIT: process.env.FRONT_URL_OLD_VISIT,

  MAX_SESSIONS: process.env.MAX_SESSIONS || 5,

  PRIVAT_BANK_API: process.env.PRIVAT_BANK_API,

  SENDGRID_API_KEY: process.env.SENDGRID_API_KEY,
  SEND_GRID_TO_EMAIL: process.env.SEND_GRID_TO_EMAIL,
  SENDGRID_FROM_EMAIL: process.env.SENDGRID_FROM_EMAIL,
  MANAGER_EMAIL: process.env.MANAGER_EMAIL,

  AWS_S3_ACCESS_KEY: process.env.AWS_S3_ACCESS_KEY,
  AWS_S3_SECRET_KEY: process.env.AWS_S3_SECRET_KEY,
  AWS_S3_BUCKET_NAME: process.env.AWS_S3_BUCKET_NAME,
  AWS_S3_REGION: process.env.AWS_S3_REGION,
  AWS_S3_ACL: process.env.AWS_S3_ACL,
  AWS_S3_ENDPOINT: process.env.AWS_S3_ENDPOINT,

  NODE_ENV: process.env.NODE_ENV || "development",
};
